# ===== SQL SERVER LOCAL =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=estore_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SouqMa2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===== MONGODB =====
spring.data.mongodb.uri=mongodb://localhost:27017/estore_nosql
spring.data.mongodb.database=estore_nosql

# ===== SERVER =====
server.port=8080
spring.web.cors.allowed-origins=http://localhost:5173
spring.devtools.restart.enabled=false